services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: drcpractice_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./vendor:/var/www/html/vendor
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - db
    networks:
      - drcpractice_network
    environment:
      - APP_ENV=dev
      - DATABASE_URL=mysql://drcpractice_user:drcpractice_password@db:3306/drcpractice_db

  webserver:
    image: nginx:alpine
    container_name: drcpractice_webserver
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - drcpractice_network

  db:
    image: mysql:5.7
    container_name: drcpractice_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: drcpractice_db
      MYSQL_USER: drcpractice_user
      MYSQL_PASSWORD: drcpractice_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - drcpractice_network

volumes:
  dbdata:
    driver: local
  vendor:
    driver: local

networks:
  drcpractice_network:
    driver: bridge